### ISSUE TITLE
Tuples - STL

### ISSUE THREAD

**Issue by rohitkumar9710** [rohitkumar9710/CP-almanac#1]
### Enter topic name -
STL

### Enter sub-topic name
Tuples

<br><br>

### Templates for reference - [.md](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **30%** plagiarized. <br>
- [x] If my document is found to be more than **30%** plagiarized, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project to add/remove my document wherever/whenever is found necessary. <br>

**Comment by mihir1739** [comment]
What needs to be done here? Please assign this issue to me !

**Comment by rohitkumar9710** [comment]
@mihir1739  You have to provide a document on the subtopic mentioned belonging to the topic explaining the subtopic exclusively adhering to the format given [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md) . Are you sure you wanna claim this?

**Comment by Sanath91009** [comment]
Interested in this issue . So it would be best if you assign it to me
Thanks

**Comment by ZackkWolf** [comment]
Interested to take up this task. Please assign this to me.

**Comment by rohitkumar9710** [comment]
@mihir1739 

 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%201%20STL/Tuples)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 06/12/2021 11:59 hrs after that it could be assigned to someone else.

**Comment by rohitkumar9710** [comment]
@mihir1739 
All txt files have been replaced with markdown files for enabling the insertion of pictures. Note this please.

**Comment by re4lvanshsingh** [comment]
could I work on this issue? or is it closed?

**Comment by rohitkumar9710** [comment]
@Sanath91009 
 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%201%20STL/Tuples)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 08/12/2021 23:59 hrs after that it could be assigned to someone else.
