### ISSUE TITLE
Manacher's Algorithm - Strings

### ISSUE THREAD

**Issue by rohitkumar9710** [rohitkumar9710/CP-almanac#109]
### Enter topic name -
Strings

### Enter sub-topic name - 
Manacher's Algorithm

<br><br>

### Templates for reference - [.md](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **30%** plagiarized. <br>
- [x] If my document is found to be more than **30%** plagiarized, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project to add/remove my document wherever/whenever is found necessary. <br>

**Comment by Code-Aditya-14** [comment]
I would like to work on this issue.

**Comment by ayushs404** [comment]
Claim!

**Comment by rohitkumar9710** [comment]
@Code-Aditya-14 

 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%207%20Strings/Palindromes)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 16/12/2021 23:59 hrs after that it could be assigned to someone else.

**Comment by khushisingh4218** [comment]
I want to work on this issue...
claim!
