### ISSUE TITLE
String Matching using Bitsets - Strings

### ISSUE THREAD

**Issue by rohitkumar9710** [rohitkumar9710/CP-almanac#115]
### Enter topic name -
Strings

### Enter sub-topic name - 
String Matching using Bitsets

<br><br>

### Templates for reference - [.md](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **30%** plagiarized. <br>
- [x] If my document is found to be more than **30%** plagiarized, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project to add/remove my document wherever/whenever is found necessary. <br>

**Comment by ayushs404** [comment]
Claim!

**Comment by rohitkumar9710** [comment]
@ayushs404

 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%207%20Strings/String%20Matching%20using%20Bitsets)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 31/12/2021 23:59 hrs after that it could be assigned to someone else.

**Comment by rohitkumar9710** [comment]
Any updates @ayushs404

**Comment by ayushs404** [comment]
I am suffering from cold and fever, will try to do it by midnight

**Comment by Sanath91009** [comment]
claim
Since the deadline is completed could you assign it to me @rohitkumar9710

**Comment by rohitkumar9710** [comment]
@Sanath91009 

 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%207%20Strings/String%20Matching%20using%20Bitsets)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 06/01/2022 23:59 hrs after that it could be assigned to someone else.
