### ISSUE TITLE
Magic Pair

### ISSUE THREAD

**Issue by rohitkumar9710** [rohitkumar9710/CP-almanac#18]
Find the bug in the solution provided in the [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Dug%20a%20Bug/Task%202)

Read the question and the solution carefully before claiming.

Adhere to the format of the pull request. Choose form 2 for this issue.

<br><br>

<br>

**Comment by ayushs404** [comment]
Interested in debugging this problem, please assign this to me.

**Comment by ayushs404** [comment]
I found the bug, corrected it, and tested it on the platform, it got accepted. Please assign to me so that I can create pull request

**Comment by rohitkumar9710** [comment]
@ayushs404 
 
Kindly update the solution file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Dug%20a%20Bug/Task%202) and don't create another.

Make sure you follow the template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 05/12/2021 23:59 hrs after that it could be assigned to someone else.
