### ISSUE TITLE
Huffman Coding - Greedy

### ISSUE THREAD

**Issue by kishlayraj-9** [rohitkumar9710/CP-almanac#19]
### Enter topic name -
Greedy

### Enter sub-topic name -
Huffman Coding

<br><br>

### Templates for reference - [.md](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **30%** plagiarized. <br>
- [x] If my document is found to be more than **30%** plagiarized, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project to add/remove my document wherever/whenever is found necessary. <br>

**Comment by ZackkWolf** [comment]
Hi there! Can I be assigned this issue??

**Comment by ZackkWolf** [comment]
Claim.

**Comment by kishlayraj-9** [comment]
@ZackkWolf 

 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%204%20Greedy/Huffman%20Coding)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 07/12/2021 11:59 hrs after that it could be assigned to someone else.

**Comment by Sunidhi-Tiwari** [comment]
Can I work on this issue??

**Comment by re4lvanshsingh** [comment]
could I work on this issue?

**Comment by re4lvanshsingh** [comment]
Claim!
