### ISSUE TITLE
Ordered Set - Policy Based Data Structures

### ISSUE THREAD

**Issue by rohitkumar9710** [rohitkumar9710/CP-almanac#2]
### Enter topic name -
Policy Based Data Structures

### Enter sub-topic name -
Ordered Set

<br><br>

### Templates for reference - [.md](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **30%** plagiarized. <br>
- [x] If my document is found to be more than **30%** plagiarized, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project to add/remove my document wherever/whenever is found necessary. <br>

**Comment by HarshBhakkad** [comment]
Can you explain what is expected here?

**Comment by rohitkumar9710** [comment]
Yes. You have to provide a document on the subtopic belonging to the topic explaining the subtopic exclusively adhering to the format [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md).

**Comment by Sanath91009** [comment]
Interested in this issue . So it would be best if you assign it to me 
Thanks

**Comment by rohitkumar9710** [comment]
@Sanath91009 
 
Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%202%20Policy%20Based%20Data%20Structures/Ordered%20Set)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 05/12/2021 23:59 hrs after that it could be assigned to someone else.

**Comment by Sanath91009** [comment]
@rohitkumar9710 
 Is the link given for the text file is correct ? I hope it is not

**Comment by rohitkumar9710** [comment]
@Sanath91009 
Thanks, I have updated the link.

**Comment by rohitkumar9710** [comment]
@Sanath91009 
All txt files have been replaced with markdown files for enabling the insertion of pictures. Note this please.

**Comment by Sanath91009** [comment]
Can I submit pdf file . I am not that familiar with markdown....
@rohitkumar9710

**Comment by rohitkumar9710** [comment]
@Sanath91009 
No. We have to maintain the uniformity. Markdown is very easy. It's very similar to HTML. See the raw version of the reference.
