### ISSUE TITLE
DFS on 2D Grid - Graphs

### ISSUE THREAD

**Issue by kishlayraj-9** [rohitkumar9710/CP-almanac#28]
### Enter topic name -
Graphs

### Enter sub-topic name - 
DFS on 2D Grid

<br><br>

### Templates for reference - [.md](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **30%** plagiarized. <br>
- [x] If my document is found to be more than **30%** plagiarized, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project to add/remove my document wherever/whenever is found necessary. <br>

**Comment by Sunidhi-Tiwari** [comment]
Interested to do this. What basically I need to do is to make a document in the specified format including some pictures, some code and a proper explanation about DFS on 2D gird? Is that all, right?

**Comment by ayushs404** [comment]
Claim!

**Comment by kishlayraj-9** [comment]
@ayushs404 

 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%205%20Graph/DFS%20on%202D%20Grid)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 07/12/2021 11:59 hrs after that it could be assigned to someone else.
