### ISSUE TITLE
Omkar and Determination

### ISSUE THREAD

**Issue by rohitkumar9710** [rohitkumar9710/CP-almanac#29]
Find the bug in the solution provided in the [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Dug%20a%20Bug/Task%203)

Read the question and the solution carefully before claiming.

### Enter the link to the question, if available on any platforms (Eg: Codeforces, CodeChef).
https://codeforces.com/contest/1586/problem/C

<br><br>

<br>

**Comment by Sanath91009** [comment]
I am interested to solve this issue

**Comment by Sanath91009** [comment]
Deadline ? @rohitkumar9710

**Comment by rohitkumar9710** [comment]
@Sanath91009  
 
Kindly update the solution file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Dug%20a%20Bug/Task%203) and don't create another.

Make sure you follow the template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 06/12/2021 11:59 hrs after that it could be assigned to someone else.
