### ISSUE TITLE
TOPOSORT - Topological Sorting

### ISSUE THREAD

**Issue by rohitkumar9710** [rohitkumar9710/CP-almanac#3]
Find the bug in the solution provided in the [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Dug%20a%20Bug/Task%201)

Read the question and the solution carefully before claiming.

### Enter the link to the question, if available on any platforms (Eg: Codeforces, CodeChef).
https://www.spoj.com/problems/TOPOSORT/

<br><br>

<br>

**Comment by yashgautam9274** [comment]
I am interested in solving this question.

**Comment by Sanath91009** [comment]
Claim

**Comment by rohitkumar9710** [comment]
@yashgautam9274
 
Kindly update the solution file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Dug%20a%20Bug/Task%201) and don't create another.

Make sure you follow the template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 04/12/2021 23:59 hrs after that it could be assigned to someone else.
