### ISSUE TITLE
Edmonds–Karp algorithm - Flows

### ISSUE THREAD

**Issue by kishlayraj-9** [rohitkumar9710/CP-almanac#4]
### Enter topic name -
Flows

### Enter sub-topic name -
Edmonds–Karp algorithm

<br><br>

### Templates for reference - [.md](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **30%** plagiarized. <br>
- [x] If my document is found to be more than **30%** plagiarized, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project to add/remove my document wherever/whenever is found necessary. <br>

**Comment by shubhamshankar28** [comment]
Claim!

**Comment by kishlayraj-9** [comment]
@shubhamshankar28 

 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%203%20Flows/Maximum%20Flow%20Algorithms)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 06/12/2021 23:59 hrs after that it could be assigned to someone else.

**Comment by shubhamshankar28** [comment]
Should I create a seperate branch for each issue or should can I use the branch that I created for the last issue?

**Comment by rohitkumar9710** [comment]
@shubhamshankar28 
Update your forked repo to ours and then do the required changes.

**Comment by shubhamshankar28** [comment]
I want to upload pictures to illustrate an example so can I delete the original text file and upload a pdf instead?

**Comment by rohitkumar9710** [comment]
@shubhamshankar28 
I have changed all txt files to md files for pictures to get inserted. Adhere to the reference md file.
