### ISSUE TITLE
Introduce yourselves in the Contributors Data [Mandatory]

### ISSUE THREAD

**Issue by rohitkumar9710** [rohitkumar9710/CP-almanac#6]
Enter your details in the JSON file `Contributors Data/participants.json` and edit one of the unused templates in the file. Do not create or delete any entry, only edit the unused ones.

Kindly avoid raising PRs with  incomplete details for that will get rejected. You can refer to the JSON file `Contributors Data/mentors.json` for more clarity. And make sure you first update your forked repo with ours before pushing and raising PR.

## This is an open issue. You don't have to claim this!

**Comment by ZackkWolf** [comment]
Hi there! I'd like to be assigned this. Please do the same.

**Comment by rohitkumar9710** [comment]
@ZackkWolf 
This is an open issue. Just edit the JSON file and raise a PR.

**Comment by Harsha351** [comment]
added my details.
