### ISSUE TITLE
Cram Time

### ISSUE THREAD

**Issue by rohitkumar9710** [rohitkumar9710/CP-almanac#62]
Find the bug in the solution provided in the [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Dug%20a%20Bug/Task%204)

Read the question and the solution carefully before claiming.

### Enter the link to the question, if available on any platforms (Eg: Codeforces, CodeChef).
https://codeforces.com/contest/1031/problem/C

<br><br>

<br>

**Comment by Code-Aditya-14** [comment]
I want to work on this issue.

**Comment by ayushs404** [comment]
Interested to work on this issue. Please assign this to me.

**Comment by rohitkumar9710** [comment]
@Code-Aditya-14 

Kindly update the solution file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Dug%20a%20Bug/Task%204) and don't create another.

Make sure you follow the template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 07/12/2021 23:59 hrs after that it could be assigned to someone else.
