### ISSUE TITLE
Ternary Search - Miscellaneous

### ISSUE THREAD

**Issue by kishlayraj-9** [rohitkumar9710/CP-almanac#63]
### Enter topic name -
Searching

### Enter sub-topic name - 
Ternary Search

<br><br>

### Templates for reference - [.md](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **30%** plagiarized. <br>
- [x] If my document is found to be more than **30%** plagiarized, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project to add/remove my document wherever/whenever is found necessary. <br>

**Comment by ayushs404** [comment]
Claim!

**Comment by kishlayraj-9** [comment]
@ayushs404 

 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%206%20Miscellaneous/Ternary%20Search)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 08/12/2021 23:59 hrs after that it could be assigned to someone else.

**Comment by Sanath91009** [comment]
Claim

**Comment by kirtan05** [comment]
Claim
