### ISSUE TITLE
Counting a substring

### ISSUE THREAD

**Issue by rohitkumar9710** [rohitkumar9710/CP-almanac#73]
Find the bug in the solution provided in the [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Dug%20a%20Bug/Task%205)

Read the question and the solution carefully before claiming.

**Comment by Sunidhi-Tiwari** [comment]
claim!

**Comment by Sanath91009** [comment]
claim

**Comment by Tanishqmalu** [comment]
claim

**Comment by ayushs404** [comment]
Claim!

**Comment by rohitkumar9710** [comment]
@Tanishqmalu 

Kindly update the solution file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Dug%20a%20Bug/Task%205) and don't create another.

Make sure you follow the template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 09/12/2021 23:59 hrs after that it could be assigned to someone else.

**Comment by Tanishqmalu** [comment]
@rohitkumar9710  i was not aware that we had to give screenshots of line where we found the bug, instead i wrote comments in front of those lines where i found bugs.  Should i make another pr?

**Comment by rohitkumar9710** [comment]
@Tanishqmalu No. It's fine!
