### ISSUE TITLE
Clique - Graph

### ISSUE THREAD

**Issue by kishlayraj-9** [rohitkumar9710/CP-almanac#75]
### Enter topic name -
Graph

### Enter sub-topic name - 
Clique

<br><br>

### Templates for reference - [.md](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **30%** plagiarized. <br>
- [x] If my document is found to be more than **30%** plagiarized, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project to add/remove my document wherever/whenever is found necessary. <br>

**Comment by ayushs404** [comment]
Claim!

**Comment by rohitkumar9710** [comment]
@ayushs404 
You are already working on an issue, which is still not closed. Cannot assign anything to you until it gets closed!

**Comment by kirtan05** [comment]
Claim.

**Comment by ayushs404** [comment]
@rohitkumar9710 Could me assign me now?

**Comment by kishlayraj-9** [comment]
@ayushs404 

 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%205%20Graph/Clique)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 11/12/2021 11:59 hrs after that it could be assigned to someone else.

**Comment by Sanath91009** [comment]
Claim

**Comment by rohitkumar9710** [comment]
@ayushs404 
You have missed the deadline we gave to you. We are giving you another 24hrs. 
You can solely work on it by 12/12/2021 11:59 hrs after that it could be assigned to someone else.

**Comment by ayushs404** [comment]
@rohitkumar9710 I was working on the issue, but I thought the deadline is 11:59 night. Misunderstood it but thanks for giving me 24 hours.
