### ISSUE TITLE
Kosaraju’s algorithm - Graph

### ISSUE THREAD

**Issue by kishlayraj-9** [rohitkumar9710/CP-almanac#97]
### Enter topic name -
Graph

### Enter sub-topic name - 
Kosaraju’s algorithm

<br><br>

### Templates for reference - [.md](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

<br>

By creating/claiming the issue or by creating PR(pull request) for this issue you agree to the below conditions -

- [x] I affirm that my document is less than **30%** plagiarized. <br>
- [x] If my document is found to be more than **30%** plagiarized, my PR(pull request) can be rejected without any prior information. <br>
- [x] I give the right to maintainers/admins/collaborators of this repository/project to add/remove my document wherever/whenever is found necessary. <br>

**Comment by amanagr6697** [comment]
Can I take this issue?

**Comment by kishlayraj-9** [comment]
@amanagr6697 

 Kindly update the markdown file in this [folder](https://github.com/rohitkumar9710/CP-almanac/tree/main/Documentation/Chapter%205%20Graph/Kosaraju%E2%80%99s%20algorithm)

Document should be strictly in this [format](https://github.com/rohitkumar9710/CP-almanac/blob/main/Documentation/Reference.md)

Make sure you follow the pull request template [here](https://github.com/rohitkumar9710/CP-almanac/blob/main/pull_request_template.md)

You can solely work on it by 12/12/2021 23:59 hrs after that it could be assigned to someone else.

**Comment by re4lvanshsingh** [comment]
Could i work on this in case @amanagr6697 fails to do so?
